services:
  - type: web
    name: guvenli-internet-asistani
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py
    envVars:
      - key: PORT
        sync: false
    healthCheckPath: /health

