# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['api.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('brand_data.json', '.'),
        ('popüler_siteler.xlsx', '.'),
        ('brand_failures.json', '.'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.logging',
        'fastapi',
        'pydantic',
        'pydantic.json',
        'pydantic.types',
        'pydantic.fields',
        'pydantic.validators',
        'pydantic.networks',
        'requests',
        'bs4',
        'whois',
        'Levenshtein',
        'PIL',
        'PIL.Image',
        'selenium',
        'selenium.webdriver',
        'selenium.webdriver.chrome',
        'selenium.webdriver.chrome.options',
        'selenium.webdriver.firefox',
        'selenium.webdriver.firefox.options',
        'selenium.webdriver.common.by',
        'selenium.common.exceptions',
        'imagehash',
        'numpy',
        'sklearn',
        'sklearn.cluster',
        'sklearn.cluster._kmeans',
        'pandas',
        'openpyxl',
        'analiz_motoru',
        'bilgi_bankasi_olusturucu',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Phishing_Defense_Backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

